### ISSUE TITLE
IMU readings

### ISSUE THREAD

**Issue by Tobias-Fischer** [prophesee-ai/prophesee_ros_wrapper#17]
Hiya,
I can see that IMU readings used to be part of the code, but then were removed. We'd like to use IMU, could it please be added back?

Many thanks,
Tobias
/cc @fervanegas

**Comment by nlyubova** [comment]
Hello,

unfortunately, the support for IMU reading has indeed been deprecated since Metavision SDK V2.1.0.
This ROS wrapper is simply a wrapper of Metavision SDK, so it doesn't support IMU anymore.

If you want to continue using IMU, then you should stick with version Metavision SDK V2.0.0 and go back in git history to get IMU reading back.
Alternatively, we can send you the format of the IMU events so that you can decode your IMU data and use it as you wish.

Hope this helps!

**Comment by Tobias-Fischer** [comment]
Dear @nlyubova, many thanks for your response. Yes, it would be great if you could send us the format of the IMU events. Just to understand, in this case we can use newer Metavision SDKs (>=2.1.0)?

**Comment by nlyubova** [comment]
as we don't support IMU anymore, so you cannot read/write them with our software >=2.1.0. We are very sorry about it.

However, we can provide you documentation on the IMU data format, so that you are free to develop your own plugin to read/process IMU if you like.

**Comment by Tobias-Fischer** [comment]
Yes please that'd be great. Could you please email it to me? tobias.fischer@qut.edu.au

**Comment by iftahnaf** [comment]
Hi @nlyubova 

Can you send me the documentation of the IMU data format? iftach@lulav.space

Thanks!

**Comment by laurentbristiel** [comment]
Hello Iftach,
I just sent you the format by email.

**Comment by analogicalnexus** [comment]
Can you also send me the documentation of the IMU data format? cmparam9@terpmail.umd.edu

**Comment by laurentbristiel** [comment]
Hello @analogicalnexus 
I just added this information in [public page of Prophesee Knowledge Center](https://support.prophesee.ai/portal/en/kb/articles/imu-data-format-in-metavision-software).
So now you should have access to it (and so will other people who are looking for it).
Hope this helps,
Laurent

**Comment by analogicalnexus** [comment]
Thank you so much @laurentbristiel.

**Comment by harmalkar** [comment]
Hi @laurentbristiel,

I'm working with @analogicalnexus to decode IMU readings from a Gen3 camera using the information which you linked. Could you provide the source code for a EVT2 decoder that we can edit to obtain IMU data using the information you provided? I tried to use [raw_evt2_decoder.h](https://github.com/prophesee-ai/openeb/blob/main/hal_openeb_plugins/include/common/raw_evt2_decoder.h) but this decoder does not work - I get a segmentation fault when using it to decode data from the Gen3.

_More details:_
I'm trying to edit [metavision_hal_viewer.cpp](https://github.com/prophesee-ai/openeb/blob/main/hal/cpp/samples/metavision_hal_viewer/metavision_hal_viewer.cpp) to print IMU data while it displays event data streaming from the Gen3. I saw that the `Metavision::EVT2::Decoder::decode_events_buffer()` function in [raw_evt2_decoder.h](https://github.com/prophesee-ai/openeb/blob/main/hal_openeb_plugins/include/common/raw_evt2_decoder.h) checks to see if an event is of type CD_OFF, CD_ON, or EXT_TRIGGER, so that seems like the right place to add a check for IMU data events.

However, when I plug the Gen3 camera into my computer and run metavision_hal_viewer, `Metavision::EVT2::Decoder::decode_events_buffer()` never gets called. It seems like this is because the decoder which the viewer uses is not `Metavision::EVT2::Decoder`.  Instead, metavision_hal_viewer.cpp calls `Metavision::I_Decoder *i_decoder = device->get_facility<Metavision::I_Decoder>();` to determine the type of decoder to use, and when I run  `std::cout << "Type of decoder: " << typeid(*i_decoder).name() << "" << std::endl;` to see which decoder it chooses, I get the following output: `"Type of decoder: N10Metavision11EVT2DecoderE"`. On the other hand, when I force the viewer to use the decoder in [raw_evt2_decoder.h](https://github.com/prophesee-ai/openeb/blob/main/hal_openeb_plugins/include/common/raw_evt2_decoder.h) by running `Metavision::I_Decoder *i_decoder = new Metavision::EVT2::Decoder(false);
std::cout << "Type of decoder: " << typeid(*i_decoder).name() << "" << std::endl;`, I get the following output: `"Type of decoder: N10Metavision4EVT27DecoderE".`

This means that the [raw_evt2_decoder.h](https://github.com/prophesee-ai/openeb/blob/main/hal_openeb_plugins/include/common/raw_evt2_decoder.h) class (4EVT27) is not the same as the decoder which metavision_hal_viewer is using to decode the data coming from the camera (11EVT2). This wouldn't be a problem in itself if [raw_evt2_decoder.h](https://github.com/prophesee-ai/openeb/blob/main/hal_openeb_plugins/include/common/raw_evt2_decoder.h) worked, because I could just force the viewer to use [raw_evt2_decoder.h](https://github.com/prophesee-ai/openeb/blob/main/hal_openeb_plugins/include/common/raw_evt2_decoder.h).

But when I try to do that, I get a segmentation fault when the viewer tries to decode the first CD event. This segmentation fault occurs at line 142 of [raw_evt2_decoder.h](https://github.com/prophesee-ai/openeb/blob/main/hal_openeb_plugins/include/common/raw_evt2_decoder.h):
`Event2D *ev_cd  = reinterpret_cast<Event2D *>(cur_raw_ev);`

Could you provide a fix for [raw_evt2_decoder.h](https://github.com/prophesee-ai/openeb/blob/main/hal_openeb_plugins/include/common/raw_evt2_decoder.h), or the source code for an alternative decoder which we can use? Once we have the source code for a working EVT2 decoder we can modify it using the other info you provided regarding IMU data.

**Comment by harmalkar** [comment]
Hi @laurentbristiel,

I have tried to use the `hal_openeb_plugins` to read the RAW data, and found that no IMU data was present in the RAW files. So I will contact support to see if I can get access to the camera plugin source code. Thanks for the quick response!
